const LivraisonData = [
    {
        N:'01',
        wilaya:'adrar',
        domicile:'1100',
        stopdesk:'800'
    },
    {
        N:'02',
        wilaya:'chlef',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'03',
        wilaya:'laghouat',
        domicile:'800',
        stopdesk:'600'
    },
    {
        N:'04',
        wilaya:'oum el bouaghi',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'05',
        wilaya:'batna',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'06',
        wilaya:'béjaia',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'07',
        wilaya:'biskra',
        domicile:'850',
        stopdesk:'600'
    },
    {
        N:'08',
        wilaya:'bechar',
        domicile:'900',
        stopdesk:'800'
    },
    {
        N:'09',
        wilaya:'blida',
        domicile:'600',
        stopdesk:'350'
    },
    {
        N:'10',
        wilaya:'bouira',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'11',
        wilaya:'tamenraset',
        domicile:'1600',
        stopdesk:'1000'
    },
    {
        N:'12',
        wilaya:'tebessa',
        domicile:'750',
        stopdesk:'600'
    },
    {
        N:'13',
        wilaya:'tlemcan',
        domicile:'800',
        stopdesk:'400'
    },
 
    {
        N:'15',
        wilaya:'tizi ouzou',
        domicile:'650',
        stopdesk:'400'
    },
    {
        N:'16',
        wilaya:'alger',
        domicile:'400',
        stopdesk:'300'
    },
    {
        N:'17',
        wilaya:'djelfa',
        domicile:'800',
        stopdesk:'600'
    },
    {
        N:'18',
        wilaya:'jijel',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'19',
        wilaya:'sétif',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'20',
        wilaya:'saida',
        domicile:'850',
        stopdesk:'400'
    },
    {
        N:'21',
        wilaya:'skikda',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'22',
        wilaya:'sidi bel abbes',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'23',
        wilaya:'annaba',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'24',
        wilaya:'guelma',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'25',
        wilaya:'constantine',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'26',
        wilaya:'médea',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'27',
        wilaya:'mostaganem',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'28',
        wilaya:"m'sila",
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'29',
        wilaya:'mascara',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'30',
        wilaya:'ouargla',
        domicile:'850',
        stopdesk:'600'
    },
    {
        N:'31',
        wilaya:'oran',
        domicile:'700',
        stopdesk:'400'
    },
    {
        N:'32',
        wilaya:'el bayedh',
        domicile:'900',
        stopdesk:'600'
    },
    {
        N:'33',
        wilaya:'ilizy',
        domicile:'indisponible',
        stopdesk:'indisponible'
    },
    {
        N:'34',
        wilaya:'bordj bou arreridj',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'35',
        wilaya:'boumerdas',
        domicile:'600',
        stopdesk:'350'
    },
    {
        N:'36',
        wilaya:'el taref',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'37',
        wilaya:'tindouf',
        domicile:'1600',
        stopdesk:'1000'
    },
    {
        N:'38',
        wilaya:'tissemsilt',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'39',
        wilaya:'el oued',
        domicile:'900',
        stopdesk:'600'
    },
    {
        N:'40',
        wilaya:'khenchla',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'41',
        wilaya:'soukahras',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'42',
        wilaya:'tipaza',
        domicile:'600',
        stopdesk:'350'
    },
    {
        N:'43',
        wilaya:'mila',
        domicile:'750',
        stopdesk:'400'
    },
    {
        N:'44',
        wilaya:'ain defla',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'45',
        wilaya:'naàma',
        domicile:'900',
        stopdesk:'600'
    },
    {
        N:'46',
        wilaya:'ain Temouchent',
        domicile:'800',
        stopdesk:'400'
    },
    {
        N:'47',
        wilaya:'ghardaia',
        domicile:'900',
        stopdesk:'600'
    },
    {
        N:'48',
        wilaya:'relizane',
        domicile:'800',
        stopdesk:'400'
    },
]


export default LivraisonData ;